name: taskit
description: "App to easily create tasks or events from any selected text in other apps."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  add_2_calendar: ^3.0.0
  google_sign_in: ^7.2.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  receive_sharing_intent: 
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true